# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "5:00"
    groups:
      monorepo-dependencies:
        patterns: "*"
    labels:
      - "automation"
      - "backport:never"
    versioning-strategy: "lockfile-only"

  - package-ecosystem: "cargo"
    directory: "/src/bootstrap/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "5:00"
    groups:
      bootstrap-dependencies:
        patterns: "*"
    labels:
      - "automation"
      - "backport:never"
    versioning-strategy: "lockfile-only"
