# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

---

name: Automatic backport
on:
  # Run from Monday to Friday at 5:00 UTC
  schedule:
    - cron: '0 5 * * 1-5'
  # Allow to run this manually from the GitHub UI
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    name: Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Ferrocene repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all the history

      - name: Install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
            python3-requests

      - name: Configure git authorship information
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Run the backport automation
        run: python3 ferrocene/tools/backport/all.py
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PYTHONUNBUFFERED: "true"
