# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

---

name: Automatic lockfile updates
on:
  # Run from Monday to Friday at 5:00 UTC
  schedule:
    - cron: '0 5 * * 1'
  # Allow to run this manually from the GitHub UI
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run:
    name: ${{ matrix.branch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        branch:
          - main

    environment: automation-update-lockfiles
    steps:
      - name: Checkout the Ferrocene repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all the history
          ref: ${{ matrix.branch }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
            python3-requests \
            python3-yaml \
            python3-jwt

      - name: Configure git authorship information
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Updating the Cargo.lock requires subtrees to be present.
      - name: Fetch submodules
        run: git submodule update --init --depth=1 --jobs=$(nproc)

      - name: Run the update-lockfiles automation
        run: python3 ferrocene/tools/update-lockfiles/update.py --automation --target ${{ matrix.branch }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          HTTP_CLONE_TOKEN: "${{ steps.github_app_auth.outputs.token }}"
